# Docker image
# Build a Docker image to deploy, run, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'petersendev/ocelot-gateway'

steps:

- task: petersendev.dotnet-global-tool-installer.DotnetGlobalToolInstaller.DotnetGlobalToolInstaller@0
  displayName: '.NET Core Global Tool'
  inputs:
    name: nbgv

- script: nbgv cloud -c -a
  displayName: Set Version
  condition: and(succeeded(), eq(variables['system.pullrequest.isfork'], false))

- script: env
  displayName: show env

- script: docker build -t $(imageName):$(NBGV_SemVer1) OcelotGateway
  displayName: docker build

- script: docker tag $(imageName):$(NBGV_SemVer1) $(imageName):latest
  displayName: docker set latest tag
  condition: and(succeeded(), eq(variables['NBGV_PublicRelease'], true))

- script: docker tag $(imageName):$(NBGV_SemVer1) $(imageName):pre
  displayName: docker set pre tag
  condition: and(succeeded(), eq(variables['NBGV_PublicRelease'], false))